<?php
$lang['home_maintext']      = "Generatia urmatoare a elementary OS este aici. Usor si frumos. Toate aplicatiile noi. Un design rafinat. Pune-ti pretul sau descarca-l gratuit.";
$lang['home_download']      = "Descarca";
$lang['home_payment']       = "Plata";
$lang['home_amount']        = "Suma";  // Amount of money
$lang['home_method']        = "Metoda";  // Method of payment
$lang['home_processor']     = "Procesor";
$lang['home_creditcard']    = "Card de credit";
$lang['home_direct']        = "Direct"; // Direct download (via HTTP)
$lang['home_luna_free']     = "Descarca Luna gratuit";
$lang['home_elementary_is'] = "elementary este:";
$lang['home_point1']        = "Comunitate condusa.";
$lang['home_expl1']         = "elementary are un scop unic: sa ofere cea mai buna experienta posibila pentru comunitatea noastra. Suntem condusi de dorinta de a fi mai buni, nu de nota de plata. Contribuitorii nu sunt orientati spre profit, ci spre scop. Contribuitorii nu sunt orientati spre profit, ci spre scop.";
$lang['home_point2']        = "Transparent si Deschis.";
$lang['home_expl2']         = "Credem in puterea open source si colaborarea globala. Asta insemnand ca oricine poate descarca, folosi, modifica, si contribui la codul sursa scris de noi, aducand fiecare ideile proprii spre realizare. Codul este dezvoltat deschis, adica este disponibil pentru revizuire, examinare si imbunatatire de zeci de mii de dezvoltatori din intreaga lume. Si toate astea, inainte de a fi instalat pe computerul tau.";
$lang['home_point3']        = "Frumos si utilizabil.";
$lang['home_expl3']         = "elementary este mesterit de designeri si dezvoltatori care cred ca, computerele sunt usor de invatat, distractive si grozave. Prin punerea designului pe primul loc, asiguram ca nu compromitem calitatea sau uzabilitatea.";
$lang['home_point4']        = "Computer modern.";
$lang['home_expl4']         = "elementary OS este o alternativa gratuita pentru Windows pentru PC si OS X pentru Macuri. Vine cu ce te-ai astepta, cum ar fi un browser rapid si un magazin de aplicatii cu mii de aplicatii. Plus inca cateva lucruri la care nu te astepti, cum ar fi upfate-uri gratuite si fara infestare cu virusi.";
$lang['home_point5']        = "Viteza";
$lang['home_expl5']         = "Luna a fost proiectat de la temelie sa fie usor. Porneste rapid, se logheaza instantaneu, si foloseste minimum de resurse astfel ca aplicatiile sa beneficieze de rapiditate. Si cu Luna, ai aceasi fundatie Linux, aleasa sa ruleze pe cele mia rapide super-computere.";
$lang['home_point6']        = "Plin de caracteristici";
$lang['home_expl6']         = "Cand instalezi elementary, nu instalezi doar un sistem de operare. you’re not just installing an operating system. Instalezi o intreaga suita de aplicatii excelent croite pentru a fi folosite in afaceri. Poti surfa foarte usor pe net, verifica email-urile, asculta muzica sau sa abordezi sarcinile zilnice.";
$lang['home_app1']          = "Cauta dupa albume, creaza playlisturi, evalueaza melodii, si vezi track-uri similare.";
$lang['home_app2']          = "Navigheaza pe Internet cu viteza folosind Google Chrome si Apple Safari.";
$lang['home_app3']          = "Conecteaza-te cu Jabber, Facebook, Google Talk, AIM, IRC, Yahoo! si multe altele.";
$lang['home_app4']          = "Vizualizeaza multiple conturi, primeste notificari pe desktop, si citeste email-urile in conversatii.";
$lang['home_app5']          = "Importa, Organizeaza, si Editeaza fotografii. Creaza un slideshow. Distribuie pe Facebook sau Flickr.";
$lang['home_app6']          = "Stai mereu in pas cu tehnologia. Primeste update-urile imediat, pentru totdeauna, pe gratis.";
$lang['home_point7']        = "Complet accesibil";
$lang['home_expl7']         = "Diferite tipuri de oameni din lume aintreaga construiesc elementary, astfel ca, nu este surprinzator faptul ca Luna este construit tinand seama de asta. Vine cu trucuri si aplicatii pentru cei cu probleme ale auzului sau vazului, precum si pentru cei cu deficiente motorii.";
$lang['home_point8']        = "Sigur si securizat";
$lang['home_expl8']         = "Luna este construit pe fundamentul de piata al Linux-ului, (acelasi soft care ruleaza pe computerele Departamentului Apararii ale SUA, Banca Chinei, si multe altele). Nu contine virusi cunoscuti, ceea ce inseamna ca nu sunt necesare aplicatii antivirus care sa incetineasca sistemul. Luna primeste update-uri de securitate imediat ce o problema este descoperita, adica siguranta este garantata.";
$lang['home_point9']        = "100% gratuit";
$lang['home_expl9']         = "elementary OS este complet gratuit, atat in termeni de pret cat si de licenta. Nu sunt costuri suplimentare, acorduri de utilizator confuze, perioade de incercare, sau protectii de copiere restrictive. Poti instala Luna pe cat de multe computere doresti sau chiar sa-l copiezi si sa-l dai prietenilor.";
$lang['home_point10']       = "Pregatit pentru aplicatii";
$lang['home_expl10']        = "elementary OS vine insotit de un magazin de aplicatii, doldora de mii de aplicatii gratuite. Poti gasi imediat ceea ce cauti fara sa-ti fie teama de vreun virus de pe web.";
$lang['home_whatis']        = "Ce este"; // Whole sentence reads "what is elementary OS?"
